In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving V5.csv to V5.csv

In [3]:
df = pd.read_csv('V5.csv')
df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [4]:
df.shape

(10000, 12)

Select all the even indexed rows from the given dataset. What is the value in the 3rd indexed column of the 0th indexed row in the selected dataframe. (row/ column indexed from zero(0) in python/pandas)

In [8]:
even_indexed_rows = df.iloc[::2]
value1 = even_indexed_rows.iloc[0, 3]
print(value1)

111440.0

In [11]:
value2 = even_indexed_rows.iloc[332, 3]
print(value2)

256200.0

In [13]:
odd_indexed_rows = df.iloc[1::2]
value_odd = odd_indexed_rows.iloc[332, 3]
print(value_odd)

352940.0

In [15]:
odd_indexed_columns = df.iloc[:,1::2]
value_odd_columns = odd_indexed_columns.iloc[100, 5]
print(value_odd_columns)

West

In [16]:
even_rows_columns = df.iloc[::2, ::2]
value_even = even_rows_columns.iloc[255,3]
value_even

'Detached House'

In [17]:
# Determine the six most recent years in the dataset
recent_years = sorted(df['Year'].unique(), reverse=True)[:6]

# Filter rows that belong to these years and count them
num_recent_rows = len(df[df['Year'].isin(recent_years)])
print(num_recent_rows)

4749

In [5]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

In [7]:
result1 = df[(df['num_rooms'] == 3) & (df['num_bathrooms'] == 3)]
num_samples_results1 = result1.shape
print(num_samples_results1)

(2730, 12)

In [10]:
result2 = df[(df['num_rooms'] == 3) | (df['num_bathrooms'] == 3)]
num_samples_results2 = result2.shape
print(num_samples_results2)

(8591, 12)

In [14]:
result3 = df[
    (df['Year'] == 2022) &
    (df['Locality'] == 'Greenwich') &
    (df['num_rooms'] == 3) &
    ((df['Face'] == 'North') | (df['Face'] == 'East'))
]
num_samples_results3 = result3.shape[0]
print(num_samples_results3)

42

In [15]:
df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [18]:
df['Date'] = pd.to_datetime(df['Date'])
august_rows = df[df['Date'].dt.month == 8]
print(august_rows.shape[0])

1050

In [19]:
average_prices = df.groupby('Locality')['Sale Price'].mean()
highest_avg_price_locality = average_prices.idxmax()
highest_avg_price_locality

'Greenwich'